apiVersion: v1
kind: Service
metadata:
  name: vote-ui
  namespace: voting
spec:
  selector:
    app: vote-ui
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
  namespace: voting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
        - name: vote-ui
          image: mohamed1780/vote-ui:v1
          ports:
            - containerPort: 80
          env:
            - name: VOTE_API_URL
              value: "http://vote:5000"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
